#               Configuration kimp3 file

# Print summary of changes and ask question before changing
interactive: True

scan:
  # List of directories to scan (comma-separated)
  # dir_list = '/media/kimifish/MediaStore/Музыка, /home/kimifish/Downloads'
  # dir_list: '/home/pi/Downloads'
  # dir_list: '/home/kimifish/kimiside@gmail.com/Music/Песенник'
  dir_list: '/home/kimifish/Downloads/Laserdance/Albums/1987 Future Generation'

  # Directory names to skip while parsing:
  skip_dirs: ['.unwanted', '.AppleDouble']

  # Empty directory deletion
  delete_empty_dirs: True

  # Files to skip while parsing and to delete while moving:
  skip_files: ['.some_useless_file']

  # Extensions for files to scan
  valid_extensions: ['.mp3', '.flac']

  # Move or copy by default:
  move_or_copy: 'copy'

  # Common album filenames to be copied/moved with albums.
  common_files:
    - 'AlbumArtSmall.jpg'
    - 'Folder.jpg'
    - 'Thumbs.db'
    - 'front.jpg'
    - 'Cover.jpg'
    - 'front.jpeg'

collection:
  # Main Music Collection Directory
  directory: '/home/kimifish/Music'

  # Check, if album is a compilation by comparing artists of each song
  compilation_test: True

  # Coefficient for compilation test.
  # How many songs of all in directory must have different artists
  # to treat it as a compilation.
  compilation_coef: 0.5

paths:
  # Patterns for creating folders relative to Music Collection Directory
  #           • %album_title                  • %song_title
  #           • %album_artist                 • %song_artist
  #           • %num_of_tracks                • %genre
  #           • %track_num                    • %year
  #           • %disc_num
  patterns:
    album: '%album_artist/%year - %album_title (CD%disc_num)/%track_num. %song_title.mp3'
    compilation: '_Сборники/%album_title (CD%disc_num)/%track_num. %song_artist - %song_title.mp3'
    genre: '_Жанры/%genre/%year. %song_artist - %song_title.mp3'

  # Cut empty tags with surrounding symbols from path pattern
  cut_empty_tags: True

  # Cut year tag from path if there is no album title. (Things like …/1982/… to …/…)
  # Works only if cut_empty_tags_from_path above is «yes».
  cut_year_only_folders: True

  # Artist tags, that are considered to be non-valid. Lowercase
  bad_artists: ['unknown artist', 'unknown', 'неизвестный исполнитель', 'неизвестный артист']

  # Move «The» from beginning to the end of artist name. The Beatles → Beatles, the
  # Or just remove it. Or leave. 'leave', 'move' or 'remove'
  the_the: 'remove'

lastfm:

  # You have to have your own unique two values for API_KEY and API_SECRET
  # Obtain yours from http://www.last.fm/api/account for Last.fm
  api_key: .env
  api_secret: .env
  discogs_token: .env

  # In order to perform a write operation you need to authenticate yourself
  username: "kimifish"
  password_hash: '3da005c0951fa144c26b14869de1ce91'

  # Autocorrection
  autocorrection: True

  # Tags below won't be added to id3 tag list.
  banned_tags: 'song, favorite artists, top artists, the best, best,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
    hit, favorite by this group, new, la la la,
    popular, increasingly popular, top 40,
    favorites, eurovision, gold,
    4 of 10 stars, 1 of 10 stars, 2 of 10 stars, 3 of 10 stars,
    5 of 10 stars, 6 of 10 stars, 7 of 10 stars, 8 of 10 stars,
    9 of 10 stars,  10 of 10 stars,
    1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 
    1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977,
    1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
    1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
    2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
    2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033,
    gay, albums i own, favorite albums, favourite albums, loved, awesome, good songs,
    1001 albums you must hear before you die, vinyl, deep purple,
    seen live, alternative, niravana - nevermind, kurt cobain,
    streamable albums, fully streamable albums, adriano, 
    top100albumsbyme, ddt, japanese,
    '

  # Merge tags from every list below to the first tag only.
  similar_tags:
    - ['70s', "70's", 'seventies', "1970's", '1970s', '70']
    - ['60s', "60's", 'sixties', "1960's", '1960s', '60']
    - ['80s', "80's", 'eighties', "1980's", '1980s', '80']
    - ['90s', "90's", 'nineties', "1990's", '1990s', '90']
    - ['punk rock', 'punk-rock', 'punk/rock']
    - ['pop rock', 'pop-rock', 'pop/rock', 'rockpop', 'poprock']
    - ['folk rock', 'folk-rock']
    - ['folk', 'folc']
    - ['euro pop', 'europop', 'euro-pop']
    - ['dance', 'dance pop', 'dance-pop']
    - ['disco', 'euro disco', 'euro-disco']
    - ['female vocalist', 'female vocals', 'female vocal', 'female vocalists']
    - ['male vocalist', 'male vocals', 'male vocalists', 'male vocal']
    - ['electroswing', 'electro swing', 'electro-swing']
    - ['nu jazz', 'nu-jazz']
    - ['electronic', 'electronica']
    - ['french', 'france', 'french artists']
    - ['indie', 'indie rock', 'indie-rock']
    - ['rock', 'alternative rock', 'alt rock', 'alternative-rock',]
    - ['russian', 'russia', 'russian artists']

  # If tag matches regex pattern, it will be accepted as key.
  similar_tags_patterns:  # NOT WORKING
    'punk rock': "punk.*rock"

tags:

  # Library reading tags (eyed3 or taglib):
  tag_reader: "eyed3"

  # Check and try to correct bad and unused tags:
  check_tags: True

logging:
  # level: "INFO"
  level: "DEBUG"
  loggers:
    suppress:
      - "httpx"
      - "httpcore"
      - "mutagen"
      - "pylast"
    suppress_level: "WARNING"
