#               Configuration kimp3 file

# Print summary of changes and ask question before changing
interactive: True

scan:
  # List of directories to scan (comma-separated)
  # dir_list = '/media/kimifish/MediaStore/Музыка, /home/kimifish/Downloads'
  # dir_list: '/home/pi/Downloads'
  # dir_list: '/home/kimifish/kimiside@gmail.com/Music/Песенник'
  dir_list: '/home/kimifish/Downloads/Laserdance/Albums/1987 Future Generation'

  # Directory names to skip while parsing:
  skip_dirs: ['.unwanted', '.AppleDouble']

  # Empty directory deletion
  delete_empty_dirs: True

  # Files to skip while parsing and to delete while moving:
  skip_files: ['.some_useless_file']

  # Extensions for files to scan
  valid_extensions: ['.mp3', '.flac']

  # Move or copy by default:
  move_or_copy: 'copy'

  # Common album filenames to be copied/moved with albums.
  common_files:
    - 'AlbumArtSmall.jpg'
    - 'Folder.jpg'
    - 'Thumbs.db'
    - 'front.jpg'
    - 'Cover.jpg'
    - 'front.jpeg'

collection:
  # Main Music Collection Directory
  directory: '/home/kimifish/Music'

  # Check, if album is a compilation by comparing artists of each song
  compilation_test: True

  # Coefficient for compilation test.
  # How many songs of all in directory must have different artists
  # to treat it as a compilation.
  compilation_coef: 0.5

paths:
  # Patterns for creating folders relative to Music Collection Directory
  #           • %album_title                  • %song_title
  #           • %album_artist                 • %song_artist
  #           • %num_of_tracks                • %genre
  #           • %track_num                    • %year
  #           • %disc_num
  patterns:
    album: '%album_artist/%year - %album_title (CD%disc_num)/%track_num. %song_title.mp3'
    compilation: '_Сборники/%album_title (CD%disc_num)/%track_num. %song_artist - %song_title.mp3'
    genre: '_Жанры/%genre/%year. %song_artist - %song_title.mp3'

  # Cut empty tags with surrounding symbols from path pattern
  cut_empty_tags: True

  # Cut year tag from path if there is no album title. (Things like …/1982/… to …/…)
  # Works only if cut_empty_tags_from_path above is «yes».
  cut_year_only_folders: True

  # Artist tags, that are considered to be non-valid. Lowercase
  bad_artists: ['unknown artist', 'unknown', 'неизвестный исполнитель', 'неизвестный артист']

  # Move «The» from beginning to the end of artist name. The Beatles → Beatles, the
  # Or just remove it. Or leave. 'leave', 'move' or 'remove'
  the_the: 'remove'

lastfm:

  # You have to have your own unique two values for API_KEY and API_SECRET
  # Obtain yours from http://www.last.fm/api/account for Last.fm
  api_key: .env
  api_secret: .env
  discogs_token: .env

  # In order to perform a write operation you need to authenticate yourself
  username: "kimifish"
  password_hash: '3da005c0951fa144c26b14869de1ce91'

  # Autocorrection
  autocorrection: True

  # Allowed genre tags
  genres: ['acoustic', 'acoustic rock', 'afrobeat', 'afropop', 'alternative', 
    'alternative metal', 'alternative rock', 'ambient', 'americana', 'anarcho-punk', 
    'art pop', 'art rock', 'avant-garde', 'baroque', 'bebop', 'big band', 'black metal', 
    'bluegrass', 'blues', 'blues rock', 'bossa nova', 'breakbeat', 'britpop', 'cajun', 
    'calypso', 'celtic', 'chamber music', 'chanson', 'chillout', 'chiptune', 
    'christian rock', 'city pop', 'classic rock', 'classical', 'cloud rap', 
    'conscious rap', 'contemporary classical', 'country', 'country pop', 'country rock', 
    'crunk', 'crust punk', 'cumbia', 'dance', 'dancehall', 'dark ambient', 'dark wave', 
    'death metal', 'deathcore', 'deep house', 'delta blues', 'disco', 'dixieland', 
    'doom metal', 'downtempo', 'dream pop', 'drill', 'drone', 'drum and bass', 'dub', 
    'dubstep', 'edm', 'electro', 'electro swing', 'electronic', 'electronica', 'emo', 
    'emo rap', 'ethereal', 'eurodance', 'experimental', 'fado', 'flamenco', 'folk', 
    'folk metal', 'folk pop', 'folk punk', 'folk rock', 'free jazz', 'funk', 
    'funk rock', 'fusion jazz', 'future bass', 'g-funk', 'gabber', 'garage', 
    'garage rock', 'glam metal', 'glam rock', 'glitch', 'goa trance', 'gospel', 
    'gothic metal', 'gothic rock', 'grime', 'grindcore', 'groove metal', 'grunge', 
    'hard rock', 'hardcore', 'hardcore punk', 'hardstyle', 'heavy metal', 'hi-nrg', 
    'highlife', 'hip hop', 'horrorcore', 'house', 'hyperpop', 'idm', 'indie', 
    'indie folk', 'indie pop', 'indie rock', 'industrial', 'industrial metal', 
    'italo-disco', 'j-pop', 'j-rock', 'jam band', 'jazz', 'jazz fusion', 'jazz rap', 
    'jazz rock', 'jug band', 'k-pop', 'krautrock', 'latin', 'latin jazz', 'latin pop', 
    'liquid funk', 'lo-fi', 'lounge', 'madchester', 'makossa', 'math rock', 'medieval', 
    'melodic death metal', 'merengue', 'metal', 'metalcore', 'minimal', 'moombahton', 
    'motown', 'neo-classical', 'neo-soul', 'neotraditional country', 'new age', 
    'new jack swing', 'new wave', 'no wave', 'noise', 'noise rock', 'northern soul', 
    'nu jazz', 'nu metal', 'oi!', 'opera', 'orchestral', 'outlaw country', 'p-funk', 
    'philly soul', 'phonk', 'polka', 'pop', 'pop punk', 'pop rock', 'post-hardcore', 
    'post-metal', 'post-punk', 'post-rock', 'power metal', 'power pop', 
    'progressive house', 'progressive metal', 'progressive rock', 'psychedelic', 
    'psychedelic rock', 'psychobilly', 'punk', 'punk blues', 'punk rock', 'qawwali', 
    'queercore', 'r&b', 'ragga', 'raga rock', 'ragtime', 'rap', 'rap metal', 
    'rap rock', 'reggae', 'reggaeton', 'renaissance', 'retrowave', 'riot grrrl', 'rock', 
    'rock and roll', 'rockabilly', 'roots reggae', 'salsa', 'samba', 'screamo', 
    'shoegaze', 'singer-songwriter', 'ska', 'ska punk', 'skiffle', 'smooth jazz', 
    'soca', 'soft rock', 'soul', 'southern gothic', 'southern rock', 'space rock', 
    'space synth', 'speed metal', 'spoken word', 'stoner rock', 'surf rock', 'swing', 
    'symphonic metal', 'synth pop', 'synthwave', 'tango', 'tech house', 'techno', 
    'teen pop', 'thrash metal', 'trance', 'trap', 'tribal house', 'trip hop', 
    'tropicália', 'turntablism', 'uk garage', 'vaporwave', 'viking metal', 'vocal jazz', 
    'west coast hip hop', 'western swing', 'world music', 'zouk', 'zydeco',
    ]

  # Tags below won't be added to id3 tag list.
  banned_tags: 'song, hit, new, la la la, popular, increasingly popular,
    eurovision, gold, gay, albums i own, loved, awesome, good songs,
    vinyl, deep purple, seen live, alternative, niravana - nevermind, kurt cobain,
    adriano, top100albumsbyme, ddt,
    '
  banned_tags_patterns:
    - '\d+'
    - '[the |]best'
    - 'best of.*'
    - 'discovered in.*'
    - 'top [\d+|artists|cd]'
    - '\d+ of \d+ .*'
    - '.*streamable.*'
    - 'favou?rite.*'
    - '.* before you die'
    - '.*seixas'

  # Banned artists from tags.
  banned_artists_from_tags:
    'rock': ['abba',]
    'japanese': ['ддт',]

  # Merge tags from every list below to the first tag only.
  similar_tags:
  - ['latin', 'latin music']
  - ['house', 'house music']
  # Genres and Subgenres

  # If tag matches regex pattern, first will be used.
  similar_tags_patterns:

    # Decades
  - ['50s', "(?:50|50\\'s|fifties|1950\\'s?)"]
  - ['60s', "(?:60|60\\'s|sixties|1960\\'s?)"]
  - ['70s', "(?:70|70\\'s|seventies|1970\\'s?)"]
  - ['80s', "(?:80|80\\'s|eighties|1980\\'s?)"]
  - ['90s', "(?:90|90\\'s|nineties|1990\\'s?)"]
  - ['00s', "(?:00\\'s|two thousands|2000s|2000-2009|aughts|noughties)"]
  - ['dark wave', 'dark[-\s/]?wave']
  - ['dark synth', 'dark[-\s/]?synth']
  - ['punk rock', 'punk[-\s/]?rock']
  - ['female vocalist', 'female voc.*']

  # Genres
  - ['rock', 'rock\smusic']
  - ['alternative rock', '(?:alt\srock|alternative-rock)']
  - ['punk rock', 'punk[-\s/]?rock']
  - ['pop rock', '(?:pop[-\s/]?rock|rockpop|poprock)']
  - ['synth pop', '(?:synthpop|synth-pop|synth[-\s]?dance)']
  - ['electronic', 'electronica']
  - ['techno', 'tehno']
  - ['smooth jazz', 'smooth-jazz']
  - ['classical', 'classical music']
  - ['rap', 'rap music']
  - ['soul', 'soul music']
  - ['reggae', 'reggae music']
  - ['latin', 'latin music']
  - ['house', 'house music']
  - ['trance', 'trance music']
  - ['dubstep', 'dubstep music']
  - ['jazz', 'jazz music']
  - ['blues', 'blues music']
  - ['pop', 'pop music']
  - ['punk', 'punk music']

  # Descriptive
  - ['male vocalist', 'male\s(?:vocals|vocalists?)']
  - ['instrumental', '(?:no\svocals|instrumental\smusic)']
  - ['female vocalist', 'female\svoc.*']

  # Regional
  - ['american', "(?:usa|united states|american artists?)"]
  - ['british', "(?:uk|united kingdom|british artists?)"]
  - ['french', "(?:france|french artists?)"]
  - ['german', "(?:germany|german artists?)"]
  - ['italian', "(?:italy|italian artists?)"]
  - ['japanese', "(?:japan|japanese artists?)"]
  - ['korean', "(?:korea|korean artists?)"]
  - ['russian', "(?:russia|russian artists?)"]

  # Electronic/Dance
  - ['synthwave', "(?:synth[-\\s]?wave|synth wave)"]
  - ['space synth', "(?:space-synth|spacesynth|spacewave|space wave)"]
  - ['dance', "(?:dance pop|dance-pop)"]
  - ['disco', "(?:euro disco|euro-disco)"]
  - ['electroswing', "(?:electro swing|electro-swing)"]
  - ['nu jazz', "nu-jazz"]

  # Rock/Metal variants
  - ['folk rock', 'folk[-\s]?rock']
  - ['hard rock', 'hard[-\s]?rock']
  - ['progressive rock', '(?:prog\srock|progressive-rock)']
  - ['garage rock', 'garage[-\s]?rock']
  - ['metal', '(?:heavy\smetal|metal\smusic)']

  # Pop variants
  - ['euro pop', '(?:europop|euro-pop)']
  - ['k-pop', 'kpop']
  - ['j-pop', 'jpop']

  # Other genres
  - ['hip hop', '(?:hip-hop|hiphop)']
  - ['r&b', '(?:r\sand\sb|rhythm\sand\sblues|rnb)']
  - ['classical', 'classical\smusic']
  - ['country', '(?:country\smusic|country\sand\swestern)']
  - ['folk', 'folc']

  # Recording types
  - ['live', '(?:live\sperformance|concert\srecording)']
  - ['studio', 'studio\srecording']
  - ['remix', '(?:remixed|remix\sversion)']
  - ['cover', '(?:cover\sversion|covered\sby)']
  - ['original', 'original\sversion']
  - ['acoustic', '(?:unplugged|acoustic\smusic)']

  # Other Tags
  - ['indie', '(?:indie[-\s]?rock|indie-rock)']

tags:

  # Library reading tags (eyed3 or taglib):
  tag_reader: "eyed3"

  # Check and try to correct bad and unused tags:
  check_tags: True

logging:
  # level: "INFO"
  level: "DEBUG"
  loggers:
    suppress:
      - "httpx"
      - "httpcore"
      - "mutagen"
      - "pylast"
    suppress_level: "WARNING"
