#!/usr/bin/python
#  -*- coding: utf-8 -*-
import kimp3

# print song.config_vars
# print

s = kimp3.ScanDir(u'/media/kimifish/MediaStore/Музыка/Wipers/1981 - Youth Of America')
# s = kimp3.ScanDir(u'/home/kimifish/Музыка/Браво')

for songdir in s.directories_list:
    for song in songdir.songList:
        song.build_newpath()
        print (song.newfilepath)

s.copy_all_dirs()

